### ISSUE TITLE
Can't find ice FTDI USB device

### ISSUE THREAD

**Issue by silver-deguz** [matthiasbock/ice40up5k-playground#2]
I figured it was better to open a new ticket issue. I ran into this problem when trying to load the program onto the board. 

"iceprog - Can't find iCE FTDI USB device" 

I looked at the Icestorm website where they mention this issue and tried their solution but had no luck. I wonder if it has to with this being the ICE40-UP5K board and not the ICE40-HX8K.

Did you encounter a similar issue?

Thanks!

**Comment by matthiasbock** [comment]
Yes, that should be a different issue.

What was the command you typed in?

Have you verified that the board is connected and recognized by looking for the FTDI chip in the output of "lsusb"?

If it's there, have you checked the user's permissions to access the device?

**Comment by silver-deguz** [comment]
Verified that the board is being recognized with the FTDI chip. I thought I had permissions to flash the device but I apparently did not. I was able to flash the device by running sudo on the bin file where the iceprog is located.
